// Generated by https://quicktype.io

export interface MultasResponse {
    idmultas:    number;
    unidad:      number;
    fecha:       string;
    estadoMulta: EstadoMulta;
}

export enum EstadoMulta {
    Pendiente = "Pendiente",
}
